name: 'ecma-262-biblio'

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 'publish ecma262-biblio'
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'tc39/ecma262' }}

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@56f291b2a0d9e3bce72634356ae949b1e054b9f8
        name: 'nvm install lts/* && npm ci'
        with:
          node-version: lts/*
          use-npm-ci: true
      - name: Publish biblio
        run: scripts/publish-biblio.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_FOR_TC39_USER }}
